### ISSUE TITLE
Enhancement: show new tab with result even if two files are identically

### ISSUE THREAD

**Issue by cachaito** [colinta/SublimeFileDiffs#63]
Hi! I recently discovered some strange behaviour: I tried to diff two files in separated tabs but there was no reactions at all. After second I noticed, that those files are the same. I think there should be a simple notification that there is no diff in files being checked?

Best regards,
Bartek

**Comment by colinta** [comment]
These is a message, but it's subtle. In the status bar, bottom left corner, it will say "No differences"

Maybe using the new tooltip api would be better!

I'm probably not going to address this myself, but I would accept a PR, as long as it isn't very obtrusive (like opening a new file just to report "no diffs")

**Comment by cachaito** [comment]
In my humble opinion a new tab with short info about no differences in two files is nothing obtrusive. Furthermore it is a way better solution than little info in bottom of the screen. No reaction when comparing two files it only gives user a confuse and the feeling that something is not working.

**Comment by colinta** [comment]
That's fine, and I would encourage you to fork the repo, add this feature, submit a PR, and we'll discuss it.
