### ISSUE TITLE
reverse not working with file_diff_clipboard

### ISSUE THREAD

**Issue by tgrey1** [colinta/SublimeFileDiffs#68]
I'm new to both sublime and this plugin, so I'll say that this could be a user error on my part, but I can't seem to get file_diff_clipboard to work reversed so that clipboard contents are considered "old"

All three of these seem to generate the same diff output for me:
{ "keys": ["ctrl+alt+d"], "command": "file_diff_clipboard" },
{ "keys": ["ctrl+alt+shift+d"], "command": "file_diff_clipboard", "args": {"reverse": false} },
{ "keys": ["super+ctrl+alt+shift+d"], "command": "file_diff_clipboard", "args": {"reverse": true} }

This was testing on ST3 build 3083 on OSX 10.7.5

**Comment by colinta** [comment]
Looks like the `reverse` option was removed at some point!

**Comment by colinta** [comment]
Nope, I'm wrong - it was never supported in the first place.  One sec, though, this will be easy to add.

**Comment by colinta** [comment]
Pushed 2.6.0
