### ISSUE TITLE
Highlight intraline diff in Selection

### ISSUE THREAD

**Issue by kulldox** [colinta/SublimeFileDiffs#71]
Hi, I love you plugin. Especially the Selection diff function. Good job.

Now, I have one little question. Is there a way to show the exact chars that are different (Highlight intraline changes)? Like highlight them with a different color or something. Now it just tells you that the lines are different.

Other than this, works awesome.

**Comment by colinta** [comment]
Answering to an issue from _six_ years ago! Haha, oops. Well, this plugin uses the builtin python diff lib, which doesn't support intra-line changes... so, sadly no this is out of scope for this plugin.
