### ISSUE TITLE
[Feature Req] show diff between two opened windows

### ISSUE THREAD

**Issue by ctf0** [colinta/SublimeFileDiffs#76]
atm you can get the diff from 2 tabs within the same window, but is it possible to add an option to compare between 2 tabs in 2 windows ex

![demo](https://cloud.githubusercontent.com/assets/7388088/22851402/4c82c668-f029-11e6-9414-9eaaa35e8374.jpg)

this is basically a way to show a diff between 2 projects side by side

**Comment by colinta** [comment]
Sure, not terribly hard to add, but I doubt I'll add it myself (I've never needed this feature, personally).  If you look at the code, the *"diff tabs"* feature populates an array of items, and presents that array in a picker.  The same could be done by iterating over all the windows and all the views in those windows, and presenting that list.

**Comment by ctf0** [comment]
after some playing , i found that this could be achieved-ish by using `file_diff_previous`

**Comment by Starli0n** [comment]
You can add those shortcuts:

`Default (OSX).sublime-keymap`
```
{ "keys": ["ctrl+super+d"],  "command": "file_diff_previous" },
```

`Default (Windows).sublime-keymap`
```
{ "keys": ["ctrl+alt+d"],  "command": "file_diff_previous" },
```

- Select the first file you want to compare
- Select the second file you want to compare with
- Activate the shortcut for comparing the two files

It works on `ST2` and `ST3` and on separate windows.
