### ISSUE TITLE
Would it make sense archiving the previous versions?

### ISSUE THREAD

**Issue by stdedos** [colinta/SublimeFileDiffs#82]
A mix between a discussion thread and a feature request.

My main "urge" is to keep searching programs (`locate`, VoidTools Everything etc) from "spamming" my search list. _I understand that this can be worked-around with e.g. negative filters_

Apart from that, it would be also argued that it makes moving the directory between systems / deletion easier, less "wasted space" (especialy when most of the files are `<<4KB`) ... generally fixes small-files issues.

The decreased "managing" cost would be vastly amortized and _I assume_ it will go unnoticed under normal usage

**Comment by colinta** [comment]
I'm sorry, but I don't understand what you're talking about - what does this have to do with this plugin?

**Comment by stdedos** [comment]
Ouch :/ Wrong plugin

Apologies
