### ISSUE TITLE
SublimeDiff gives unexisting differences

### ISSUE THREAD

**Issue by brupelo** [colinta/SublimeFileDiffs#84]
I'm trying to find out why SublimeDiff is giving me unexisting difference when copying content from a hard-disk file to a Sublime temporal view, please take a look:

![showcase](https://dl.dropboxusercontent.com/s/4jvqq6gcmu1h5yx/2018-07-03_16-56-54.gif)

As you can see in the demo, diffing between 2 temporal views will give no differences while if I try to diff between the file vs the temporal view I'll get "unexisting" differences. Why is that? And the most important... how can i fix the behaviour?

I've got installed v2.8.0

**Comment by colinta** [comment]
Interesting, is this on Windows?  My guess: newline characters.

**Comment by brupelo** [comment]
@colinta Indeed, windows7, here's the [file](https://www.dropbox.com/s/mgoicwozb2buned/Makefile?dl=1) I've used on the above test. Please let me know if you can also reproduce it, it'd be great to narrow this one as diffing between temporal views and files is a very very common feature when regenerating projects/makefiles/... :D

Thanks in advance

**Comment by brupelo** [comment]
@colinta I think I've discovered what's going on ... if you take a look to the original file, it contains tabs... and for some obscure reason when I paste the content into a new file these tabs are magically converted to spaces... which is the main reason why the plugin will report these differences :(

**Comment by brupelo** [comment]
@colinta I guess I shouldn't use the below settings anymore:

	"translate_tabs_to_spaces": true,
	"trim_trailing_white_space_on_save": true,

:(

**Comment by brupelo** [comment]
Anyway, it seems this was an issue on my side because of my settings configuration, nothing wrong with the plugin so far.

For more info, here's the [docs](http://docs.sublimetext.info/en/latest/customization/settings.html)

**Comment by colinta** [comment]
Ahh interesting... yeah I'm not sure there's much I could do to try to predict this.  I wish the built in diff package had a way to ignore whitespace differences, that's something people have requested in the past. ¯\_(ツ)_/¯
