### ISSUE TITLE
Add support for sublime's builtin incremental diff

### ISSUE THREAD

**Issue by AmjadHD** [colinta/SublimeFileDiffs#90]
It would be handy to add support for incrementally diffing two files.
Sorry, I'm too lazy to make a PR, but feel free to copy the code from my [IncrementalDiff plugin](https://packagecontrol.io/packages/IncrementalDiff)  (I'm going to delete it afterwards).

**Comment by colinta** [comment]
This is interesting... what would this feature look like, given the usual workflow of `FileDiffs`. 

I don't use the IncrementalDiff feature, tbh; it's too subtle to be of much use to me, I prefer good ol' diffs.

**Comment by AmjadHD** [comment]
you're working on a file and would like a permanent view of the changes between it and another file, clipboard, etc as you're working on it.
you can then quickly navigate the diff hunks, and show individual or all changes.
the diff is also more precise (as in by character instead of by line) than `git diff`.
It's also for the sake of completeness that I suggested this.

**Comment by 0xdevalias** [comment]
Docs link for reference:

- https://www.sublimetext.com/docs/incremental_diff.html
  - > Sublime Text includes a built-in diff functionality that tracks changes to files being edited. The diff calculation is incremental, tracking each buffer modification as it is performed. It does not require the file be stored in a version control system, such as Git.
    > 
    > The exact location of each addition, modification and deletion is tracked. This is used to display markers in the gutter, allow navigation between each change, display inline diffs and allow for reverting changes.
    > 
    > Diffs are calculated against the version of the file on disk, but [Diff Markers](https://www.sublimetext.com/docs/git_integration.html#diff-markers) can be configured to diff against HEAD, and the API allows files to be diffed against any content.

**Comment by colinta** [comment]
> Sorry, I'm too lazy to make a PR

I'm not convinced that these two plugins are aligned well enough to merge, and since I'm not swimming in free time to explore the implementation, I'm going to close this issue. 🤷 Always open to review a PR!
