### ISSUE TITLE
Show settings side by side

### ISSUE THREAD

**Issue by 0xdevalias** [colinta/SublimeFileDiffs#91]
Currently there are separate menu options for showing the default and user settings, which open that file individually:

![image](https://github.com/colinta/SublimeFileDiffs/assets/753891/d83cc097-a26d-4302-98fa-79154945b3ba)

It would be really useful if there was a single menu item that opened both at once in a side by side view, similar to how Sublime's own settings are shown:

![image](https://github.com/colinta/SublimeFileDiffs/assets/753891/f4e6794c-14cd-4494-bcf3-b60e9d0a51f9)

**Comment by colinta** [comment]
I don't see an obvious way to implement this using the ST API – do you? 

This seems like a nice-to-have (PR welcome) not a missing critical feature (aka sorry-not-sorry but I don't have the time to implement nice-to-haves 😬).

**Comment by 0xdevalias** [comment]
> I don't see an obvious way to implement this using the ST API – do you?

I haven't looked deeply into it, but it seems to be a pretty common pattern among other extensions. Maybe I can dig up a reference from one.

> aka sorry-not-sorry but I don't have the time to implement nice-to-haves

Totally understandable.

**Comment by colinta** [comment]
If there's an implementation out there, I would copy/paste that "open both settings" code in a heartbeat. 👍 

thanks for understanding lack of time to explore this in depth myself 😢

**Comment by 0xdevalias** [comment]
> but I'll try and remember to open a PR for this later today if I get the chance

Opened PR:

- https://github.com/colinta/SublimeFileDiffs/pull/92
